agnostic_nms: false
amp: true
augment: true
auto_augment: randaugment
batch: 16
bgr: 0.0
box: 7.5
cache: true
cfg: null
classes: null
close_mosaic: 10
cls: 0.5
conf: null
copy_paste: 0.1
copy_paste_mode: flip
cos_lr: true
cutmix: 0.3
data: /Users/kgrover2/Documents/cucumber_HTP/data/clean_dataset/data.yaml
degrees: 10.0
deterministic: true
device: auto
dfl: 1.5
dnn: false
dropout: 0.1
dynamic: false
embed: null
epochs: 500
erasing: 0.4
exist_ok: true
fliplr: 0.5
flipud: 0.1
format: torchscript
fraction: 1.0
freeze: null
half: true
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
imgsz: 640
int8: false
iou: 0.7
keras: false
kobj: 1.0
line_width: null
lr0: 0.001
lrf: 0.01
mask_ratio: 4
max_det: 300
mixup: 0.3
mode: train
model: yolo12s.pt
momentum: 0.937
mosaic: 1.0
multi_scale: true
name: cucumber_traits_v2
nbs: 64
nms: false
opset: null
optimize: false
optimizer: AdamW
overlap_mask: true
patience: 50
perspective: 0.001
plots: true
pose: 12.0
pretrained: true
profile: false
project: models/production
rect: false
resume: false
retina_masks: false
save: true
save_conf: false
save_crop: false
save_dir: models/production/cucumber_traits_v2
save_frames: false
save_json: false
save_period: 25
save_txt: false
scale: 0.9
seed: 42
shear: 2.0
show: false
show_boxes: true
show_conf: true
show_labels: true
simplify: true
single_cls: false
source: null
split: val
stream_buffer: false
task: detect
tracker: botsort.yaml
translate: 0.2
val: true
verbose: true
vid_stride: 1
visualize: false
warmup_bias_lr: 0.1
warmup_epochs: 5.0
warmup_momentum: 0.8
weight_decay: 0.0005
workers: 8
workspace: null
